owner: PatLittle
repo: Consultations-Tracker
sites:
- name: Co-development of a new Indigenous Broadcasting Policy
  url: https://crtc.gc.ca/eng/archive/2019/2019-217.htm
- name: Share your thoughts about closed captioning of programming from online streaming
    services
  url: https://crtc.gc.ca/eng/consultation/cc.htm
- name: Share your thoughts on Canadian content for audio services
  url: https://crtc.gc.ca/eng/consultation/audio.htm
- name: Proposed Amendments to the Export Permits Regulations
  url: https://www.international.gc.ca/trade-commerce/controls-controles/expor/backgrounder-amendments-epr-information-modification-rle.aspx?lang=eng
- name: Consultation to inform the regulatory development to support the implementation
    of An Act to amend the National Defence Act and to make related and consequential
    amendments to other Acts
  url: https://www.canada.ca/en/department-national-defence/services/benefits-military/legal-services/victim-service-offence.html
- name: Consultation to inform the regulatory development to support the implementation
    of An Act to amend the National Defence Act and to make related and consequential
    amendments to other Acts
  url: https://www.canada.ca/en/department-national-defence/services/benefits-military/legal-services/victim-service-offence.html
- name: Social systems professional services
  url: www.marsdd.com
- name: Draft Capital Adequacy Requirements (CAR) Guideline
  url: https://www.osfi-bsif.gc.ca/en/guidance/guidance-library/consultation-draft-capital-adequacy-requirements-car-guideline?utm_medium=email&utm_source=web&utm_campaign=qr&utm_term=2025-02
- name: National Strategy to Combat Human Trafficking (HT) Targeted Engagement Annual
    Engagement
  url: https://www.canada.ca/en/services/policing/police/crime-and-crime-prevention/human-trafficking-smuggling/nggmnt-rnwd-hmntrffckng.html
- name: Targeted Stakeholder Engagement to Inform Canada’s Public Safety Broadband
    Network (PSBN)
  url: https://www.canada.ca/en/services/policing/emergencies/consultation-governance-framework-psbn.html
- name: Oceans Protection Plan
  url: https://www.letstalktransportation.ca/OPP
- name: OPP - Understanding the Cumulative Effects of Marine Vessel Activity on Coastal
    and Marine Environments
  url: https://letstalktransportation.ca/understanding-the-effects-of-marine-vessel-activity-on-coastal-environments
- name: 'OPP: Northern Low-Impact Shipping Corridors'
  url: https://www.dfo-mpo.gc.ca/about-notre-sujet/engagement/2021/shipping-corridors-navigation-eng.html
- name: Adopting Global Technical Regulations 13 and 20 for Zero Emission Vehicle
    Safety (Electric Battery and Hydrogen)
  url: https://N/A
- name: Fee Modernisation Initiative for Transport Canada's Owned and Operated Ports
  url: https://N/A
- name: Proposed amendments to the Environmental Response Regulations
  url: TBD
- name: Canadian Marine Advisory Council - Fall 2025
  url: https://tc.canada.ca/en/marine/canadian-marine-advisory-council-cmac-engagement-opportunity-marine-safety-security-regulations#canada_gazette_1
- name: 'Discussion Paper: Potential regulations to increase access to marine emergency
    services and to improve response to pollution incidents'
  url: https://tc.canada.ca/en/corporate-services/consultations/discussion-paper-potential-regulations-increase-access-marine-emergency-services-improve-response-pollution-incidents
- name: Proposed regulatory project on administrative monetary penalties under the
    Marine Liability Act and parts of the Wrecked, Abandoned or Hazardous Vessels
    Act
  url: https://tc.canada.ca/en/corporate-services/consultations/proposed-regulatory-project-administrative-monetary-penalties-under-marine-liability-act-parts-wrecked-abandoned-hazardous-vessels-act
- name: Updating the Saskatoon John G Diefenbaker International Airport Zoning Regulations
  url: https://N/A
status-website:
  theme: night
  baseUrl: /Consultations-Tracker
  logoUrl: https://www.canada.ca/etc/designs/canada/wet-boew/assets/wmms-blk.svg
  name: GC Automated Consultations QA
  introTitle: '[Consulting with Canadians](https://www.canada.ca/en/government/system/consultations/consultingcanadians.html)
    is Canada''s one stop shop for finding Consultations.'
  introMessage: This tool scans all Consultations from [Consulting with Canadians](https://www.canada.ca/en/government/system/consultations/consultingcanadians.html)
    which are listed as either Open or Planned and checks to ensure the profile page
    is an active link. No server required — This tool automatically get's the list
    of consultations from [Open Government](https://open.canada.ca/data/en/dataset/7c03f039-3753-4093-af60-74b0f7b2385d/resource/92bec4b7-6feb-4215-a5f7-61da342b2354)
    and tries each link every 4 hours.
  customBodyHtml: "<h3>Consultations Starting +/- 5 days from today</h3><table border=\"\
    1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n \
    \     <th>registration_number</th>\n      <th>title_en</th>\n      <th>start_date</th>\n\
    \      <th>end_date</th>\n      <th>status</th>\n      <th>owner_org</th>\n  \
    \  </tr>\n  </thead>\n  <tbody>\n  </tbody>\n</table><h3>Consultations Ending\
    \ +/- 5 days from today</h3><table border=\"1\" class=\"dataframe\">\n  <thead>\n\
    \    <tr style=\"text-align: right;\">\n      <th>registration_number</th>\n \
    \     <th>title_en</th>\n      <th>start_date</th>\n      <th>end_date</th>\n\
    \      <th>status</th>\n      <th>owner_org</th>\n    </tr>\n  </thead>\n  <tbody>\n\
    \  </tbody>\n</table><h3>Consultations Listed as Open that should be closed</h3><table\
    \ border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\"\
    >\n      <th>registration_number</th>\n      <th>title_en</th>\n      <th>start_date</th>\n\
    \      <th>end_date</th>\n      <th>status</th>\n      <th>owner_org</th>\n  \
    \  </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>687</td>\n      <td>Adopting\
    \ Global Technical Regulations 13 and 20 for Zero Emission Vehicle Safety (Electric\
    \ Battery and Hydrogen)</td>\n      <td>2024-07-29</td>\n      <td>2025-01-31</td>\n\
    \      <td>O</td>\n      <td>tc</td>\n    </tr>\n    <tr>\n      <td>1023</td>\n\
    \      <td>Discussion Paper: Potential regulations to increase access to marine\
    \ emergency services and to improve response to pollution incidents</td>\n   \
    \   <td>2024-10-02</td>\n      <td>2025-01-31</td>\n      <td>O</td>\n      <td>tc</td>\n\
    \    </tr>\n    <tr>\n      <td>1069</td>\n      <td>Proposed regulatory project\
    \ on administrative monetary penalties under the Marine Liability Act and parts\
    \ of the Wrecked, Abandoned or Hazardous Vessels Act</td>\n      <td>2024-11-20</td>\n\
    \      <td>2025-01-20</td>\n      <td>O</td>\n      <td>tc</td>\n    </tr>\n \
    \   <tr>\n      <td>C-000048</td>\n      <td>Share your thoughts about closed\
    \ captioning of programming from online streaming services</td>\n      <td>2024-11-18</td>\n\
    \      <td>2024-12-20</td>\n      <td>O</td>\n      <td>crtc</td>\n    </tr>\n\
    \    <tr>\n      <td>D00039</td>\n      <td>Targeted Stakeholder Engagement to\
    \ Inform Canada’s Public Safety Broadband Network (PSBN)</td>\n      <td>2024-07-01</td>\n\
    \      <td>2024-10-31</td>\n      <td>O</td>\n      <td>ps-sp</td>\n    </tr>\n\
    \    <tr>\n      <td>698</td>\n      <td>Digitizing the Travel Journey at Airports</td>\n\
    \      <td>2023-04-01</td>\n      <td>2024-03-31</td>\n      <td>O</td>\n    \
    \  <td>tc</td>\n    </tr>\n    <tr>\n      <td>C-CANSOF-002</td>\n      <td>Social\
    \ systems professional services</td>\n      <td>2022-03-01</td>\n      <td>2022-08-31</td>\n\
    \      <td>O</td>\n      <td>dnd-mdn</td>\n    </tr>\n    <tr>\n      <td>C-JAG-21Q1-11</td>\n\
    \      <td>Consultation to inform the regulatory development to support the implementation\
    \ of An Act to amend the National Defence Act and to make related and consequential\
    \ amendments to other Acts</td>\n      <td>2021-05-13</td>\n      <td>2022-08-03</td>\n\
    \      <td>O</td>\n      <td>dnd-mdn</td>\n    </tr>\n    <tr>\n      <td>C-JAG-21Q2-18</td>\n\
    \      <td>Consultation to inform the regulatory development to support the implementation\
    \ of An Act to amend the National Defence Act and to make related and consequential\
    \ amendments to other Acts</td>\n      <td>2021-05-13</td>\n      <td>2022-08-03</td>\n\
    \      <td>O</td>\n      <td>dnd-mdn</td>\n    </tr>\n    <tr>\n      <td>C-0000558</td>\n\
    \      <td>Proposed Amendments to the Export Permits Regulations</td>\n      <td>2022-06-18</td>\n\
    \      <td>2022-07-18</td>\n      <td>O</td>\n      <td>dfatd-maecd</td>\n   \
    \ </tr>\n    <tr>\n      <td>530</td>\n      <td>OPP - Understanding the Cumulative\
    \ Effects of Marine Vessel Activity on Coastal and Marine Environments</td>\n\
    \      <td>2017-09-20</td>\n      <td>2022-01-10</td>\n      <td>O</td>\n    \
    \  <td>tc</td>\n    </tr>\n  </tbody>\n</table>"
  navbar:
  - title: GitHub
    href: https://github.com/$OWNER/$REPO
  - title: Consulting with Canadians
    href: https://www.canada.ca/en/government/system/consultations/consultingcanadians.html
  - title: Consultations Open Data
    href: https://open.canada.ca/data/en/dataset/7c03f039-3753-4093-af60-74b0f7b2385d
workflowSchedule:
  graphs: 0 0 * * *
  responseTime: 0 23 * * *
  staticSite: 0 1 * * *
  summary: 0 0 * * *
  updateTemplate: 0 0 * * *
  updates: 0 3 * * *
  uptime: 0 */4 * * *
