owner: PatLittle
repo: Consultations-Tracker
sites:
- name: 'Accessibility Standards Canada: 2026 to 2028 Accessibility Plan'
  url: https://accessible.canada.ca/consultations/accessibility-plan-and-progress-report
- name: White River First Nations
  url: https://www.rcaanc-cirnac.gc.ca/eng/1511969222951/1529103469169
- name: Use of digital tools at the border
  url: https://www.cbsa-asfc.gc.ca/services/border-tech-frontiere/modern-eng.html
- name: Administrative Monetary Penalty System Review
  url: https://www.cbsa-asfc.gc.ca/trade-commerce/amps/menu-eng.html
- name: Regulatory Framework Plan
  url: https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cer-rec.gc.ca%2Fen%2Fabout%2Fhow-we-regulate%2Fplans-for-regulatory-framework%2F&data=05%7C02%7CMichelle.Shabits%40cer-rec.gc.ca%7Cec1c386ebea64452821d08dc41ebb1b9%7C56e9b8d38a3549abbdfc27de59608f01%7C0%7C0%7C638457728797041411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=tKxvqtPetzkvcXlETiyyf51rWnRpUftsM2o2U5IySO4%3D&reserved=0
- name: Regulated Industry Engagement
  url: https://www.cer-rec.gc.ca/en/consultation-engagement/stakeholder-engagement/regulated-industry-engagement/index.html
- name: 'Share your thoughts: Risk mitigation options for the importation of honey
    bee packages from the United States'
  url: https://inspection.canada.ca/en/about-cfia/transparency/consultations-and-engagement/honey-bee-packages-united-states
- name: 'Share your thoughts: Proposed new livestock feed ingredient –Propionibacterium
    freudenreichii culture dehydrated'
  url: N
- name: 'Share your thoughts: Proposed amendments to the Tables of Permissible Claims
    for Feed Labels'
  url: N
- name: Public consultation on proposed regulatory changes in Canada Gazette Part
    I amending the Plant Breeders' Rights Regulations
  url: N
- name: Changing Narrative Fund
  url: https://www.canada.ca/en/canadian-heritage/campaigns/changing-narratives-fund.html
- name: 2022-23 Consultations on renewal of the Museum Policy
  url: https://www.canada.ca/en/canadian-heritage/campaigns/renewal-museum-policy.html
- name: Co-development of a new Indigenous Broadcasting Policy
  url: https://crtc.gc.ca/eng/archive/2019/2019-217.htm
- name: Share your thoughts about closed captioning of programming from online streaming
    services
  url: https://crtc.gc.ca/eng/consultation/cc.htm
- name: Share your thoughts on improving public interest participation
  url: https://crtc.gc.ca/eng/consultation/public.htm
- name: Baffinland Steensby Railway Consultation
  url: https://otc-cta.gc.ca/eng/consultation/baffinland-steensby-railway-consultation
- name: 'TRC Call to Action 66: Moving from Pilot Project to Long-Term Implementation'
  url: Not available
- name: National Infrastructure Assessment
  url: https://www.infrastructure.gc.ca/nia-eni/index-eng.html
- name: 'Share your ideas: Blackwater Project'
  url: https://www.canada.ca/en/environment-climate-change/services/managing-pollution/sources-industry/mining/metal-diamond-mining-effluent-regulation/blackwater-consultation.html
- name: Consultation Document on the Risk Management of Short-chain, Medium-chain
    and Long-chain chlorinated alkanes
  url: https://canada.ca/en/environment-climate-change/corporate/transparency/consultations/risk-management-chlorinated-alkanes.html
- name: Proposed Coal Mining Effluent Regulations
  url: https://www.canada.ca/en/environment-climate-change/services/managing-pollution/sources-industry/mining-effluent/proposed-coal-mining-effluent-regulations.html
- name: 'Consultation on Amending the List of Species under the Species at Risk Act:
    Terrestrial Species January 2025'
  url: https://canada-preview.adobecqms.net/en/environment-climate-change/services/species-risk-public-registry/consultation-documents/part-3-consultation-amending-terrestrial-species-list-sara-summary-jan-2025.html
- name: 'Share your thoughts: Participate in the risk assessment process for GloFish®
    Corydoras'
  url: https://www.canada.ca/en/environment-climate-change/corporate/transparency/consultations/risk-assessment-process-glofish-corydoras.html
- name: Path forward for evaluating policy options for managing the accumulation of
    oil sands mine water in tailings ponds
  url: https://www.canada.ca/en/environment-climate-change/corporate/transparency/consultations/discussion-paper-crown-indigenous-working-group-2025.html
- name: Proposed ticketing for the enforcement of a fisheries offence under the Fisheries
    Act
  url: TBD
- name: Whitby Harbour Remediation Project
  url: https://www.dfo-mpo.gc.ca/sch-ppb/whitby/index-eng.html
- name: Proposed Amendments to the Export Permits Regulations
  url: https://www.international.gc.ca/trade-commerce/controls-controles/expor/backgrounder-amendments-epr-information-modification-rle.aspx?lang=eng
- name: Consultation on Cellulose (from powdered corn cobs) and its associated end-use
    products, Proposed Re-evaluation Decision PRVD2025-04
  url: https://www.canada.ca/en/health-canada/services/consumer-product-safety/pesticides-pest-management/public/consultations/proposed-re-evaluation-decisions/2025/cellulose-powdered-corn-cobs.html
- name: 'Consultation: Towards a pathway for health products containing cannabidiol'
  url: https://www.canada.ca/en/health-canada/programs/consultation-towards-pathway-products-containing-cannabidiol.html
- name: Consultation on fatty acid cluster and its associated end-use products, Proposed
    Re-evaluation Decision PRVD2025-05
  url: https://www.canada.ca/en/health-canada/services/consumer-product-safety/pesticides-pest-management/public/consultations/proposed-re-evaluation-decisions/2025/fatty-acid-cluster.html
- name: Consultation on metaldehyde, Proposed Maximum Residue Limit PMRL2025-06
  url: https://www.canada.ca/en/health-canada/services/consumer-product-safety/pesticides-pest-management/public/consultations/proposed-maximum-residue-limit/2025/metaldehyde.html
- name: Regulations Amending the Immigration and Refugee Protection Regulations (Temporary
    Foreign Workers)
  url: https://gazette.gc.ca/rp-pr/p1/2021/2021-07-10/html/reg2-eng.html
- name: York Factory First Nation Ten Shilling Aerodrome Project Public NoticeComments
    Invited on the Summary of the Initial Project Description
  url: https://iaac-aeic.gc.ca/050/evaluations/proj/89488?culture=en-CA
- name: York Factory First Nation Ten Shilling Aerodrome ProjectPublic noticeParticipant
    Funding Available
  url: https://iaac-aeic.gc.ca/050/evaluations/document/161560?culture=en-CA
- name: Indian Oil and Gas Regulations - Phase II
  url: http://www.pgic-iogc.gc.ca/eng/1471964522302/1471964567990
- name: Indigenous Procurement Modernization (including Procurement Strategy for Aboriginal
    Business)
  url: https://www.aadnc-aandc.gc.ca/eng/1554218527634/1554218554486
- name: 'Developing laws and regulations for First Nations drinking water and wastewater:
    engagement 2022/2023'
  url: Developing laws and regulations for First Nations drinking water and wastewaterengagement
    2022/2023 (sac-isc.gc.ca)
- name: 'Engagement 2023: Updating the Protocol For Centralised Drinking Water Systems
    in First Nations communities'
  url: https://www.sac-isc.gc.ca/eng/1689939603075/1689939693020
- name: Competition Bureau invites feedback on changes to the Textile Labelling and
    Advertising Regulations
  url: https://www.ic.gc.ca/eic/site/cb-bc.nsf/eng/h_00142.html
- name: 'Canada Gazette, Part I: Public Consultations on proposed changes to the Patent
    Rules and Trademark Regulations in regards to the creation of the College of Patent
    Agents and Trademark Agents , as part of Budget Implementation Act, 2018, No.
    2.'
  url: Not yet available
- name: Notice No. TIPB-001-2024 — Petition to the Governor in Council concerning
    Telecom Decision CRTC 2023-358
  url: https://canadagazette.gc.ca/rp-pr/p1/2024/2024-04-27/pdf/g1-15817.pdf
- name: Amendments to Directive No 11R3, Surplus Income Directive
  url: https://ised-isde.canada.ca/site/office-superintendent-bankruptcy/en/public-consultations
- name: Consultation on a Policy, and Licensing, and Technical Framework for Supplemental
    Mobile Coverage by Satellite
  url: https://ised-isde.canada.ca/site/spectrum-management-telecommunications/en/learn-more/key-documents/consultations/consultation-policy-licensing-and-technical-framework-supplemental-mobile-coverage-satellite
- name: Salmon aquaculture transition in British Columbia
  url: https://ised-isde.canada.ca/site/ised/en/salmon-aquaculture-transition-british-columbia
- name: Consultation on the implementation of the Global Cross-Border Privacy Rules
    (CBPR) Forum certifications in Canada
  url: https://ised-isde.canada.ca/site/ised/en/public-consultations/consultation-implementation-global-cross-border-privacy-rules-cbpr-forum-certifications-canada
- name: Indigenous Advisory Circle
  url: https://library-archives.canada.ca/eng/corporate/about-us/our-partners/Pages/indigenous-advisory-circle.aspx
- name: Stakeholders' Forum
  url: https://library-archives.canada.ca/eng/corporate/about-us/our-partners/pages/stakeholders-forum.aspx
- name: Services Consultation Committee
  url: https://library-archives.canada.ca/eng/corporate/about-us/our-partners/Pages/services-consultation-group.aspx
- name: Youth Advisory Council
  url: https://library-archives.canada.ca/eng/corporate/about-us/our-partners/Pages/youth-advisory-council.aspx
- name: Consultation to inform the regulatory development to support the implementation
    of An Act to amend the National Defence Act and to make related and consequential
    amendments to other Acts
  url: https://www.canada.ca/en/department-national-defence/services/benefits-military/legal-services/victim-service-offence.html
- name: Consultation to inform the regulatory development to support the implementation
    of An Act to amend the National Defence Act and to make related and consequential
    amendments to other Acts
  url: https://www.canada.ca/en/department-national-defence/services/benefits-military/legal-services/victim-service-offence.html
- name: Social systems professional services
  url: www.marsdd.com
- name: Indigenous Ministerial Arrangements Regulations
  url: https://www.rncanengagenrcan.ca/en/content/development-new-indigenous-ministerial-arrangements-regulations
- name: Internal Liquidity Adequacy Assessment Process (ILAAP) discussion paper
  url: https://www.osfi-bsif.gc.ca/en/guidance/guidance-library/pillar-2-liquidity-funding-risks-designing-internal-liquidity-adequacy-assessment-process-canadian?utm_source=web&utm_medium=email&utm_campaign=qr&utm_term=2025-05
- name: Draft Liquidity Adequacy Requirements (LAR) Guideline
  url: https://www.osfi-bsif.gc.ca/en/guidance/guidance-library/liquidity-adequacy-requirements-lar-guideline-2026?utm_source=web&utm_medium=email&utm_campaign=qr&utm_term=2025-05
- name: Draft Minimum Capital Test (MCT) Guideline
  url: https://www.osfi-bsif.gc.ca/en/guidance/guidance-library/minimum-capital-test-guideline-2026?utm_source=web&utm_medium=email&utm_campaign=qr&utm_term=2025-05
- name: General Regulations under the Canada National Marine Conservation Areas Act
  url: https://www.letstalknmcas.ca/
- name: Notice of Mooring Restrictions – Ontario Waterways - Trent-Severn Waterway
    National Historic Site
  url: https://parks.canada.ca/lhn-nhs/on/trentsevern/info/avis-restrictions-amarrage-notice-mooring-restrictions/
- name: Notice of Mooring Restrictions – Ontario Waterways - Rideau Canal National
    Historic Site
  url: https://parks.canada.ca/lhn-nhs/on/rideau/info/avis-restrictions-amarrage-notice-mooring-restrictions/
- name: Fortress of Louisbourg National Historic Site Management Plan
  url: https://www.pc.gc.ca/en/lhn-nhs/ns/louisbourg/info/plan
- name: Visitor Use Management - Jasper National Park
  url: https://www.letstalkmountainparks.ca/visitor-use-management-jasper
- name: Visitor Use Management - Lake Louise Area
  url: https://www.letstalkmountainparks.ca/lakelouisevum
- name: Updating the Community Plans for Field, B.C. and Lake Louise, Alberta
  url: https://www.letstalkmountainparks.ca/communityplanupdates
- name: Saguenay-St. Lawrence Marine Park expansion project
  url: https://parcmarin.qc.ca/consultations/home/
- name: Public Engagement on the Strategic Environmental Assessment for the Town of
    Banff railway lands area redevelopment plan
  url: www.letstalkmountainparks.ca/town-of-banff-area-redevelopment-plan-strategic-environmental-assessment
- name: Town of Banff Railways Lands Area Redevelopment Plan - Term of Reference for
    Strategic Environmental Assessment
  url: https://www.letstalkmountainparks.ca/town-of-banff-area-redevelopment-plan-strategic-environmental-assessment/widgets/194782/documents
- name: Consultation – Proposed national park in the Teetł’it Gwinjik (Peel River)
    Watershed
  url: https://parks.canada.ca/pn-np/cnpn-cnnp/teetlit-gwinjik-peel
- name: Engagement process on the development of a strategic environmental assessment
    for the Town of Banff Community Plan
  url: https://banffviewpoints.ca/communityplan
- name: National Strategy to Combat Human Trafficking (HT) Targeted Engagement Annual
    Engagement
  url: https://www.canada.ca/en/services/policing/police/crime-and-crime-prevention/human-trafficking-smuggling/nggmnt-rnwd-hmntrffckng.html
- name: Targeted Stakeholder Engagement to Inform Canada’s Public Safety Broadband
    Network (PSBN)
  url: https://www.canada.ca/en/services/policing/emergencies/consultation-governance-framework-psbn.html
- name: PSPC Controlled Goods Program’s Industry Engagement Committee (IEC)
  url: https://www.tpsgc-pwgsc.gc.ca/pmc-cgp/pipmc-secgp-eng.html
- name: Three-year Departmental Accessibility Plan
  url: https://www.canada.ca/en/public-services-procurement/corporate/accessibility.html
- name: Public Lands for Homes
  url: https://www.canada.ca/en/public-services-procurement/services/infrastructure-buildings/public-lands-homes.html
- name: Multifactor Productivity Application
  url: https://www.statcan.gc.ca/eng/consultation/2019/mpa
- name: Statistics Canada Client Survey 2022
  url: https://www.statcan.gc.ca/en/consultation/2022/sccs2022
- name: Census of the Environment Program
  url: https://www.statcan.gc.ca/en/consultation/2022/coep
- name: Missing persons data standards consultative engagement
  url: https://www.statcan.gc.ca/en/consultation/2023/missing-persons-data-standards
- name: Invitation to participate in the revision of the North American Industry Classification
    System (NAICS) Canada
  url: https://www.statcan.gc.ca/en/consultation/2023/naics
- name: Invitation to participate in the revision of the North American Product Classification
    System (NAPCS) Canada
  url: https://www.statcan.gc.ca/en/consultation/2023/napcs
- name: Invitation to participate in the revision of the Classification of Instructional
    Programs (CIP) Canada
  url: https://www.statcan.gc.ca/en/consultation/2024/cip
- name: Invitation to participate in the revision of the National Occupational Classification
    (NOC)
  url: https://www.statcan.gc.ca/en/consultation/2024/noc
- name: Participate in the permanent consultation for the revision of the Canadian
    Research and Development Classification (CRDC)
  url: https://www.statcan.gc.ca/en/consultation/2025/crdc
- name: Share your input on Measures to Collect Health Information with the Centre
    for Direct Health Measures
  url: https://www.statcan.gc.ca/en/consultation/2025/measures-collect-health-information
- name: Contribute to Statistics Canada's Web modernization Journey
  url: https://www.statcan.gc.ca/en/consultation/2025/web-modernization-journey
- name: Watchlist 2020 mid-cycle consultation with industry
  url: https://www.tsb.gc.ca/eng/qui-about/relation.html
- name: Watchlist 2025 mid-cycle consultations with industry
  url: https://www.tsb.gc.ca/eng/surveillance-watchlist/2022.html
- name: Oceans Protection Plan
  url: https://www.letstalktransportation.ca/OPP
- name: OPP - Understanding the Cumulative Effects of Marine Vessel Activity on Coastal
    and Marine Environments
  url: https://letstalktransportation.ca/understanding-the-effects-of-marine-vessel-activity-on-coastal-environments
- name: 'OPP: Northern Low-Impact Shipping Corridors'
  url: https://www.dfo-mpo.gc.ca/about-notre-sujet/engagement/2021/shipping-corridors-navigation-eng.html
- name: Adopting Global Technical Regulations 13 and 20 for Zero Emission Vehicle
    Safety (Electric Battery and Hydrogen)
  url: https://N/A
- name: Fee Modernisation Initiative for Transport Canada's Owned and Operated Ports
  url: https://N/A
- name: Proposed amendments to the Environmental Response Regulations
  url: TBD
- name: Canadian Marine Advisory Council - Fall 2025
  url: https://tc.canada.ca/en/marine/canadian-marine-advisory-council-cmac-engagement-opportunity-marine-safety-security-regulations#canada_gazette_1
- name: 'Discussion Paper: Potential regulations to increase access to marine emergency
    services and to improve response to pollution incidents'
  url: https://tc.canada.ca/en/corporate-services/consultations/discussion-paper-potential-regulations-increase-access-marine-emergency-services-improve-response-pollution-incidents
- name: Proposed regulatory project on administrative monetary penalties under the
    Marine Liability Act and parts of the Wrecked, Abandoned or Hazardous Vessels
    Act
  url: https://tc.canada.ca/en/corporate-services/consultations/proposed-regulatory-project-administrative-monetary-penalties-under-marine-liability-act-parts-wrecked-abandoned-hazardous-vessels-act
- name: Updating the Saskatoon John G Diefenbaker International Airport Zoning Regulations
  url: https://N/A
- name: Creating Canada’s 6th  National Action Plan on Open Government
  url: https://letstalkopengovernment.ca/
- name: Artificial Intelligence Strategy for the Government of Canada
  url: https://forms.office.com/r/4FqMrh8U43
- name: Ministerial Advisory Groups • Recognition  •  Families  • Care and Support
    • Policy •  Health and Well-being • Service Excellence and Transition
  url: https://www.veterans.gc.ca/en/about-vac/public-engagement/ministerial-advisory-groups
status-website:
  theme: night
  baseUrl: /Consultations-Tracker
  logoUrl: https://www.canada.ca/etc/designs/canada/wet-boew/assets/wmms-blk.svg
  name: GC Automated Consultations QA
  introTitle: '[Consulting with Canadians](https://www.canada.ca/en/government/system/consultations/consultingcanadians.html)
    is Canada''s one stop shop for finding Consultations.'
  introMessage: This tool scans all Consultations from [Consulting with Canadians](https://www.canada.ca/en/government/system/consultations/consultingcanadians.html)
    which are listed as either Open or Planned and checks to ensure the profile page
    is an active link and tries each link every 4 hours. In addition to uptime monitoring,
    several handy reports are generated such as Consultations starting and ending
    soon, consultations overdue to start, consulations open beyond their end date,
    etc.
  navbar:
  - title: GitHub
    href: https://github.com/$OWNER/$REPO
  - title: Consulting with Canadians↗️
    href: https://www.canada.ca/en/government/system/consultations/consultingcanadians.html
  - title: Consultations Open Data↗️
    href: https://open.canada.ca/data/en/dataset/7c03f039-3753-4093-af60-74b0f7b2385d
  - title: Consultations Tracker Reports
    href: https://patlittle.github.io/Consultations-Tracker/report.html
  - title: Consultations Change Log Reports
    href: https://patlittle.github.io/Consultations-Tracker/changelog.html
workflowSchedule:
  graphs: 0 0 * * *
  responseTime: 0 23 * * *
  staticSite: 0 1 * * *
  summary: 0 0 * * *
  updateTemplate: 0 0 * * *
  updates: 0 3 * * *
  uptime: 0 */4 * * *
